// src/errors/errorType.ts

export enum ErrorType {
  PROFILE_NOT_FOUND,
  DELETE_PROFILE_FAILED,
  EXCHANGE_NOT_FOUND,
  INVALID_PRICE,
  INVALID_QUANTITY,
  INVALID_COMMAND,
  TOO_MANY_ARGUMENTS,
  INVALID_MARKET_ORDER,
  INVALID_LIMIT_ORDER,
  INVALID_STOP_ORDER,
  CONFIG_WRITE_ERROR,
}
